kafka_config:
  bootstrap_servers: "localhost:9092"
  topic: "clickstream_events"
  starting_offsets: "earliest"

schema_registry:
  url: "http://localhost:8081"

windowing:
  timestamp_field: "event_time"
  window_duration: "10 seconds"
  slide_duration: "5 seconds"
  watermark_delay: "10 seconds"

storage:
  output_mode: "append"
  trigger_processing_time: "5 seconds"
  url_aggregates_path: "projects/realtime/clickstream/output_data/url_counts"
  user_aggregates_path: "projects/realtime/clickstream/output_data/user_counts"
  checkpoint_base_dir: "projects/realtime/clickstream/checkpoints"
