# projects/essentials/BUILD
python_sources(
    name="lib",
)

pex_binary(
    name="word_count",
    entry_point="word_count.py",
)

pex_binary(
    name="employee_partition",
    entry_point="employee_partition_by_hire_date.py",
)
